name: Rystem.Nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment: Rystem
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{secrets.NET_VERSION}}
          
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Rystem/Rystem.csproj
          PACKAGE_NAME: Rystem
          VERSION_FILE_PATH: src/Rystem/Rystem.csproj
          VERSION_REGEX: <Version>(.*)<\/Version>
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
